apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: corporate-service
  name: corporate-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: corporate-service
  template:
    metadata:
      labels:
        app: corporate-service
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: apps
                    operator: In
                    values:
                      - "true"
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - env:
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: corporate-secrets
                  key: postgres_host
            - name: POSTGRES_PORT
              value: "5434"
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: corporate-secrets
                  key: postgres_database
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: corporate-secrets
                  key: postgres_password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: corporate-secrets
                  key: postgres_user
            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: corporate-secrets
                  key: rabbitmq_host
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: corporate-secrets
                  key: rabbitmq_user
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: corporate-secrets
                  key: rabbitmq_password
            - name: HTTP_PORT
              value: ":80"
          image: gitlab.udevs.io:5050/macbro/mb_corporate_service:latest
          name: corporate-service
          imagePullPolicy: Always
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: corporate-service
  namespace: microservices
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: corporate-service
